config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "todos#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	belongs_to :user


	validates :title, :body, presence: true

	validates :title, length: {minimum: 4, maximum: 200, message: "name too short/long (4/200)"} 

    validates :title, uniqueness: true 




end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :todos

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
  end

  def show
    @todo = Todo.find(params[:id]) 
  end

  def new
    @todo = Todo.new
  end

  def create

    @todo = Todo.create(todo_params)
    @todo.user_id = current_user.id
    if @todo.save
      redirect_to @todo
    else
      render :new
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update(todo_params)
      redirect_to @todo
    else
      render :edit
    end
  end

  def destroy
    Todo.destroy(params[:id])
    redirect_to todos_url
  end

  protected
  def todo_params
    params.require(:todo).permit(:title, :body,:box, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoKeeperApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<p class="navbar-text pull-right">
  	

  		<% if user_signed_in? %>
  		Logged in as <strong><%= current_user.email %></strong>.
  		<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  		<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  		<% else %>

		<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>


  	</p>




  	<% if notice %>
  		<p class="alert alert-success"> <%= notice %> </p>
  	<% end %>

  	<% if alert %>
  		<p class="alert alert-danger"> <%= alert %> </p>
  	<% end %>


    <%= yield %>


  </body>
</html>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>

  <h3><%= pluralize(@todo.errors.count, "error") %> prohibitied this to-do from being saved: </h3>

  <ul>
    <% @todo.errors.full_messages.each do |message| %>
      <li><%= message %> </li>
    <% end %>

  </ul>

<% end %>




<%= form_for(@todo) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.check_box :box %>

  <%= f.submit %>


<% end %>

app/views/todos/_todo.html.erb
<div class="todo">
  <p>Title: <strong><%= todo.title %></strong></p>
  <p>What to actuallly do: <strong><%= todo.body %></strong></p>
  <%= check_box_tag :box %>	
  <br>
  <%= link_to "Show Page", todo if action_name == "index" %> ||
  <%= link_to "Edit Page", edit_todo_path(todo) %>
</div>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>

<%= render "form" %>

app/views/todos/index.html.erb
<h1>All Todos</h1>





<%= render @todos %>
<br>

<%= link_to "New Todo", new_todo_path %> ||
<%= link_to "Home Page", root_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<h1>Todo Show Page</h1>

  <%= render @todo %>

<br>

<%= link_to "Back", todos_path %>
 <br>

<%= link_to "Destroy", @todo, method: :delete, data: { confirm: "Are you sure?" } %>